Events.OnGameStart.Add(function ()
	print("SERVER LOADED OPTIONS:")
	print("checkbox1 = ", ZomboLewdConfig.ModOptions.options.box1)
	print("checkbox2 = ", ZomboLewdConfig.ModOptions.options.box2)
end)